export enum DataClassName {
    TOKEN = "TOKEN",
    PAYMULTISIGN = "PAYMULTISIGN",
    CONTACTINFO = "CONTACTINFO",
    MYHOMEADDRESS = "MYHOMEADDRESS",
    UPLOADFILE = "UPLOADFILE",
    VOS = "VOS",
    SERVERURL = "SERVERURL",
    LANG = "LANG",
    BlockSolveType = "BlockSolveType",
    UserSettingDataInfo = "UserSettingDataInfo",
    OrderOpenInfo = "OrderOpenInfo",
    IdentityData = "IdentityData",
    KeyValueList = "KeyValueList",
    Prescription = "Prescription",
    Certificate = "Certificate",
}